language: node_js
node_js:
- iojs-v1
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: npm
  email: stephan@boennemann.me
  skip_cleanup: true
  api_key:
    secure: FAp9VRFyI8jUPg9goEwKkvd30jjE1i03NRdKFBVHdb9kS+Y6OU9x48hWNe9qy4E5JHTtHSkrZY2YakQYBFgvW8rCAwbb6u2RgHeMqCO+iiQ+G7p4WmbpwEaeMFri3wAn2bR/hlhLTZttDz1tBHYd+rLYgvIXuYdNLL/7yss43dI=
  on:
    branch: master
    repo: boennemann/clean-script
