language: node_js
node_js:
- iojs-v1
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: npm
  email: stephan@boennemann.me
  api_key:
    secure: g8g3eTrQ3r5e6juCuEQE3JFkjDz06YGEumH7yNZq1BWoxKWJHYz+WfS1K60zUFy3dli+Y7qDvdeVsVyGd9Y0uaq1v+E9mwFAkiEuhqz63zyL9FFVL6NSVXErCdHOa62p8+6MM/KDKDg1xOkpDXX+6DW/K4xnHAVhZn7/K8Q2wZ8=
  on:
    all_branches: true
    tags: true
    repo: boennemann/clean-script
